// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Protos/HyperMath.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace HyperMath.Grpc {
  /// <summary>
  /// The MathService service definition.
  /// </summary>
  public static partial class MathService
  {
    static readonly string __ServiceName = "MathService";

    static readonly grpc::Marshaller<global::HyperMath.Grpc.MathRequest> __Marshaller_MathRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::HyperMath.Grpc.MathRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::HyperMath.Grpc.MathReply> __Marshaller_MathReply = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::HyperMath.Grpc.MathReply.Parser.ParseFrom);

    static readonly grpc::Method<global::HyperMath.Grpc.MathRequest, global::HyperMath.Grpc.MathReply> __Method_Sum = new grpc::Method<global::HyperMath.Grpc.MathRequest, global::HyperMath.Grpc.MathReply>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Sum",
        __Marshaller_MathRequest,
        __Marshaller_MathReply);

    static readonly grpc::Method<global::HyperMath.Grpc.MathRequest, global::HyperMath.Grpc.MathReply> __Method_GetAllCalc = new grpc::Method<global::HyperMath.Grpc.MathRequest, global::HyperMath.Grpc.MathReply>(
        grpc::MethodType.ServerStreaming,
        __ServiceName,
        "GetAllCalc",
        __Marshaller_MathRequest,
        __Marshaller_MathReply);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::HyperMath.Grpc.HyperMathReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of MathService</summary>
    [grpc::BindServiceMethod(typeof(MathService), "BindService")]
    public abstract partial class MathServiceBase
    {
      /// <summary>
      /// Do a Sum
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      public virtual global::System.Threading.Tasks.Task<global::HyperMath.Grpc.MathReply> Sum(global::HyperMath.Grpc.MathRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task GetAllCalc(global::HyperMath.Grpc.MathRequest request, grpc::IServerStreamWriter<global::HyperMath.Grpc.MathReply> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for MathService</summary>
    public partial class MathServiceClient : grpc::ClientBase<MathServiceClient>
    {
      /// <summary>Creates a new client for MathService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public MathServiceClient(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for MathService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public MathServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected MathServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected MathServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      /// <summary>
      /// Do a Sum
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      public virtual global::HyperMath.Grpc.MathReply Sum(global::HyperMath.Grpc.MathRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Sum(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Do a Sum
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      public virtual global::HyperMath.Grpc.MathReply Sum(global::HyperMath.Grpc.MathRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Sum, null, options, request);
      }
      /// <summary>
      /// Do a Sum
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      public virtual grpc::AsyncUnaryCall<global::HyperMath.Grpc.MathReply> SumAsync(global::HyperMath.Grpc.MathRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SumAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Do a Sum
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      public virtual grpc::AsyncUnaryCall<global::HyperMath.Grpc.MathReply> SumAsync(global::HyperMath.Grpc.MathRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Sum, null, options, request);
      }
      public virtual grpc::AsyncServerStreamingCall<global::HyperMath.Grpc.MathReply> GetAllCalc(global::HyperMath.Grpc.MathRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetAllCalc(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncServerStreamingCall<global::HyperMath.Grpc.MathReply> GetAllCalc(global::HyperMath.Grpc.MathRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncServerStreamingCall(__Method_GetAllCalc, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override MathServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new MathServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(MathServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_Sum, serviceImpl.Sum)
          .AddMethod(__Method_GetAllCalc, serviceImpl.GetAllCalc).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, MathServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_Sum, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::HyperMath.Grpc.MathRequest, global::HyperMath.Grpc.MathReply>(serviceImpl.Sum));
      serviceBinder.AddMethod(__Method_GetAllCalc, serviceImpl == null ? null : new grpc::ServerStreamingServerMethod<global::HyperMath.Grpc.MathRequest, global::HyperMath.Grpc.MathReply>(serviceImpl.GetAllCalc));
    }

  }
}
#endregion
